# Generated by Django 3.0.1 on 2020-03-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_board_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalboardlist',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_tasks', to='personal_board_system.PersonalBoard'),
        ),
    ]
