# Generated by Django 3.0.1 on 2020-03-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_board_system', '0002_auto_20200321_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBoardCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField()),
                ('attachment', models.FileField(upload_to='')),
                ('archived', models.BooleanField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_tasks', to='personal_board_system.PersonalBoard')),
            ],
        ),
        migrations.RemoveField(
            model_name='personalboardlistcard',
            name='list',
        ),
        migrations.DeleteModel(
            name='PersonalBoardList',
        ),
        migrations.DeleteModel(
            name='PersonalBoardListCard',
        ),
    ]
