# Generated by Django 3.0.1 on 2020-06-06 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal_board_system', '0004_auto_20200321_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalboard',
            name='last_viewed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
