# Generated by Django 3.0.1 on 2020-06-06 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_board_system', '0005_personalboard_last_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalboard',
            name='last_viewed',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
