# Generated by Django 3.0.1 on 2020-06-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_board_system', '0006_auto_20200606_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalboardlistcard',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
