# Generated by Django 3.0.1 on 2020-06-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_board_system', '0007_personalboardlistcard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalboardlistcard',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
